import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "english" | "vietnamese";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LANGUAGE_STORAGE_KEY = "language";

const translations: Record<Language, Record<string, string>> = {
  english: {
    // Navigation
    "nav.home": "Home",
    "nav.messages": "Messages",
    "nav.friends": "Friends",
    "nav.groups": "Groups",
    "nav.games": "Games",
    "nav.search": "Search...",

    // Groups Page
    "groups.create": "Create Group",
    "groups.createNew": "Create New Group",
    "groups.createDescription":
        "Create a new group to connect with people who share your interests.",
    "groups.name": "Group Name",
    "groups.namePlaceholder": "Enter a name for your group",
    "groups.description": "Description",
    "groups.descriptionPlaceholder": "What is your group about?",
    "groups.privacy": "Privacy",
    "groups.privacyDescription":
        "Public groups can be found in search and anyone can join. Private groups require approval to join.",
    "groups.public": "Public",
    "groups.private": "Private",
    "groups.cancel": "Cancel",
    "groups.yourGroups": "Your Groups",
    "groups.discover": "Discover",
    "groups.events": "Events",
    "groups.upcomingEvents": "Upcoming Events",
    "groups.recentDiscussions": "Recent Discussions",
    "groups.suggested": "Suggested Groups",
    "groups.members": "members",
    "groups.join": "Join Group",
    "groups.viewGroup": "View Group",
    "groups.search": "Search groups",
    "groups.loadMore": "Load More",
    "groups.createEvent": "Create Event",
    "groups.attending": "attending",
    "groups.interested": "Interested",
    "groups.comments": "comments",
    "groups.noGroups": "You haven't joined any groups yet",
    "groups.noGroupsDescription":
        "Create a group or discover groups to connect with people who share your interests.",
    "groups.noEvents": "No upcoming events",
    "groups.noEventsDescription":
        "There are no upcoming events in your groups. Create one or check back later.",
    "groups.discussion": "Discussion",
    "groups.about": "About",
    "groups.media": "Media",
    "groups.files": "Files",
    "groups.photos": "Photos",
    "groups.addPhotos": "Add Photos",
    "groups.groupInfo": "Group Info",
    "groups.publicGroup": "Public Group",
    "groups.privateGroup": "Private Group",
    "groups.created": "Created",
    "groups.rules": "Rules",
    "groups.notifications": "Notifications",
    "groups.share": "Share",
    "groups.options": "Options",
    "groups.inviteFriends": "Invite Friends",
    "groups.inviteFriendsDescription": "Invite your friends to join this group",
    "groups.muteNotifications": "Mute Notifications",
    "groups.manageGroup": "Manage Group",
    "groups.reportGroup": "Report Group",
    "groups.leaveGroup": "Leave Group",
    "groups.leaveConfirmation": "Are you sure you want to leave this group?",
    "groups.transferOwnership": "Transfer Ownership",
    "groups.writePost": "Write something to the group...",
    "groups.searchMembers": "Search members",
    "groups.invite": "Invite",
    "groups.admin": "Admin",
    "groups.moderator": "Moderator",
    "groups.joined": "Joined",
    "groups.eventTitle": "Event Title",
    "groups.eventTitlePlaceholder": "Enter event title",
    "groups.eventDate": "Date & Time",
    "groups.eventLocation": "Location",
    "groups.eventLocationPlaceholder": "Enter event location",
    "groups.eventDescription": "Description",
    "groups.eventDescriptionPlaceholder": "Describe your event",
    "groups.eventCover": "Event Cover",
    "groups.uploadEventCover": "Upload event cover image",
    "groups.createEventDescription":
        "Create a new event for your group members",
    "groups.done": "Done",
    "groups.searchFriends": "Search friends",
    "groups.settings": "Group Settings",
    "groups.settingsDescription": "Manage your group settings and permissions",
    "groups.backToGroup": "Back to Group",
    "groups.general": "General",
    "groups.moderation": "Moderation",
    "groups.dangerZone": "Danger Zone",
    "groups.dangerZoneDescription":
        "These actions are irreversible. Please be careful.",
    "groups.basicInfo": "Basic Information",
    "groups.basicInfoDescription":
        "Set up the basic information about your group",
    "groups.groupImages": "Group Images",
    "groups.groupImagesDescription": "Upload images for your group",
    "groups.groupAvatar": "Group Avatar",
    "groups.uploadPhoto": "Upload Photo",
    "groups.uploadCover": "Upload Cover",
    "groups.addRule": "Add a rule",
    "groups.add": "Add",
    "groups.saveChanges": "Save Changes",
    "groups.changesSaved": "Changes saved successfully",
    "groups.deleteGroup": "Delete Group",
    "groups.deleteGroupDescription":
        "Once you delete a group, there is no going back. Please be certain.",
    "groups.deleteGroupTitle": "Delete Group",
    "groups.deleteGroupConfirmation":
        "Are you sure you want to delete this group? All content will be permanently removed.",
    "groups.deleteGroupWarning": "This action cannot be undone.",
    "groups.groupDeleted": "Group deleted successfully",
    "groups.transferOwnershipTitle": "Transfer Group Ownership",
    "groups.transferOwnershipDescription":
        "Select a member to transfer group ownership to",
    "groups.transfer": "Transfer",
    "groups.ownershipTransferred": "Group ownership transferred successfully",
    "groups.manageMembers": "Manage Members",
    "groups.manageMembersDescription": "Add or remove members and assign roles",
    "groups.removeMod": "Remove as Moderator",
    "groups.makeMod": "Make Moderator",
    "groups.removeModTitle": "Remove Moderator",
    "groups.makeModTitle": "Make Moderator",
    "groups.removeModDescription":
        "Are you sure you want to remove {name} as a moderator?",
    "groups.makeModDescription":
        "Are you sure you want to make {name} a moderator?",
    "groups.remove": "Remove",
    "groups.removeMemberTitle": "Remove Member",
    "groups.removeMemberDescription":
        "Are you sure you want to remove {name} from the group?",
    "groups.inviteMembers": "Invite Members",
    "groups.contentModeration": "Content Moderation",
    "groups.contentModerationDescription":
        "Manage content approval and reported content",
    "groups.approvalSettings": "Approval Settings",
    "groups.approvalSettingsDescription":
        "Control what content needs approval before being published",
    "groups.approveNewMembers": "Approve New Members",
    "groups.approveNewMembersDescription":
        "Require admin approval for new members",
    "groups.approveNewPosts": "Approve New Posts",
    "groups.approveNewPostsDescription": "Require admin approval for new posts",
    "groups.reportedContent": "Reported Content",
    "groups.reportedContentDescription":
        "Review and take action on reported content",
    "groups.reportedBy": "Reported by {name}",
    "groups.pending": "Pending",
    "groups.reviewed": "Reviewed",
    "groups.contentType": "Content Type",
    "groups.post": "Post",
    "groups.comment": "Comment",
    "groups.reason": "Reason",
    "groups.ignore": "Ignore",
    "groups.removeContent": "Remove Content",
    "groups.notificationSettings": "Notification Settings",
    "groups.notificationSettingsDescription":
        "Control what notifications you receive from this group",
    "groups.newMemberNotifications": "New Member Notifications",
    "groups.newMemberNotificationsDescription":
        "Get notified when someone joins the group",
    "groups.newPostNotifications": "New Post Notifications",
    "groups.newPostNotificationsDescription":
        "Get notified when someone posts in the group",
    "groups.commentNotifications": "Comment Notifications",
    "groups.commentNotificationsDescription":
        "Get notified when someone comments on your posts",
    "groups.eventNotifications": "Event Notifications",
    "groups.eventNotificationsDescription":
        "Get notified about upcoming events",
    "groups.createGroup": "Create Group",
    "groups.creating": "Creating...",
    "groups.rulesDescription": "Set rules for your group members to follow",
    "groups.noRulesYet":
        "No rules added yet. Add some rules to help members understand what's expected.",
    "groups.myGroups": "My Groups",
    "groups.createdByYou": "Created by You",
    "groups.adminRights": "Admin Rights",
    "groups.allGroups": "All Groups",
    "groups.owner": "Owner",
    "groups.pendingPosts": "pending posts",
    "groups.pendingMembers": "pending members",
    "groups.unreadMessages": "unread messages",
    "groups.reviewPosts": "Review Posts",
    "groups.reviewMembers": "Review Members",
    "groups.enableNotifications": "Enable Notifications",
    "groups.edit": "Edit Group",
    "groups.editGroup": "Edit Group",
    "groups.noCreatedGroups": "You haven't created any groups yet",
    "groups.noAdminGroups": "You don't have admin rights in any groups",
    "groups.adminGroupsDescription":
        "When you are made an admin of a group, it will appear here",
    "groups.noSearchResults": "No groups match your search",
    "groups.tryDifferentSearch": "Try a different search term",
    "groups.groupManagement": "Group Management",
    "groups.groupManagementDescription": "Create and manage your groups",
    "groups.invitations": "Invitations",
    "groups.noPermission": "You don't have permission to edit this group",
    "groups.backToGroups": "Back to Groups",
    "groups.savingError":
        "There was an error saving your changes. Please try again.",
    "groups.saving": "Saving...",
    "groups.title": "Groups",
    "groups.groupSettings": "Group Setting",
    "groups.changeCover": "Change Cover",

    // Search
    "search.keywords": "Keywords",
    "search.keyword": "Keyword",
    "search.people": "People",
    "search.person": "Person",
    "search.posts": "Posts",
    "search.post": "Post",
    "search.groups": "Groups",
    "search.group": "Group",
    "search.games": "Games",
    "search.game": "Game",
    "search.viewAll": "View all results",
    "search.results": "Search Results",
    "search.placeholder": "Search on PinkSocial...",
    "search.search": "Search",
    "search.all": "All",
    "search.filters": "Filters",
    "search.date": "Date",
    "search.anyTime": "Any time",
    "search.past24h": "Past 24 hours",
    "search.pastWeek": "Past week",
    "search.pastMonth": "Past month",
    "search.source": "Source",
    "search.fromFriends": "From friends",
    "search.fromGroups": "From groups",
    "search.public": "Public",
    "search.seeAll": "See all",

    // Messages
    "messages.timeline": "Timeline",
    "messages.messages": "Messages",
    "messages.conversations": "Conversations",
    "messages.searchMessages": "Search messages",
    "messages.whatsHappening": "What's happening?",
    "messages.send": "Send",
    "messages.typeMessage": "Type a message...",
    "messages.noMessages": "No messages yet.",
    "messages.noSearchResults": "No messages match your search.",
    "messages.noConversations": "No conversations yet.",
    "messages.selectConversation": "Select a conversation to start messaging",
    "messages.userAvatar": "User avatar",
    "messages.user.janeDoe": "Jane Doe",
    "messages.user.johnSmith": "John Smith",
    "messages.user.sarahJohnson": "Sarah Johnson",
    "messages.user.michaelChen": "Michael Chen",
    "messages.user.currentUser": "Current User",
    "messages.sampleText.greeting": "Hey, how are you doing today?",
    "messages.sampleText.movie":
        "Did you see the new movie that just came out?",
    "messages.sampleText.thanks": "Thanks for the help with the project!",
    "messages.sampleText.coffee": "Let's meet up for coffee next week!",
    "messages.sampleText.dayGoing": "Hey there! How's your day going?",
    "messages.sampleText.appFeatures":
        "Hi Jane! It's going pretty well, thanks for asking. Just working on some new features for the app.",
    "messages.sampleText.whatFeatures":
        "That sounds exciting! What kind of features are you working on?",
    "messages.sampleText.messagingSystem":
        "I'm adding a new messaging system with better media sharing.",
    "messages.sampleText.testIt":
        "That sounds really cool! I'd love to test it out when it's ready.",
    "messages.sampleText.notYet": "Not yet! Is it good?",
    "messages.sampleText.tuesday": "Sounds good! How about Tuesday at 2pm?",
    "messages.sampleText.usualPlace":
        "Perfect! See you then at the usual place.",

    // Time translations
    "time.just now": "just now",
    "time.1 minute ago": "1 minute ago",
    "time.2 minutes ago": "2 minutes ago",
    "time.5 minutes ago": "5 minutes ago",
    "time.10 minutes ago": "10 minutes ago",
    "time.15 minutes ago": "15 minutes ago",
    "time.30 minutes ago": "30 minutes ago",
    "time.45 minutes ago": "45 minutes ago",
    "time.1 hour ago": "1 hour ago",
    "time.2 hours ago": "2 hours ago",
    "time.3 hours ago": "3 hours ago",
    "time.4 hours ago": "4 hours ago",
    "time.5 hours ago": "5 hours ago",
    "time.yesterday": "yesterday",
    "time.2 days ago": "2 days ago",
    "time.3 days ago": "3 days ago",
    "time.last week": "last week",
    "time.2 weeks ago": "2 weeks ago",
    "time.last month": "last month",
    "time.2 months ago": "2 months ago",
    "time.3 months ago": "3 months ago",
    "time.last year": "last year",
    "time.2 years ago": "2 years ago",
    "time.3 years ago": "3 years ago",
    "time.a long time ago": "a long time ago",

    // User Profile (Existing)
    "profile.profile": "Profile",
    "profile.language": "Language",
    "profile.logout": "Logout",
    "profile.about": "About",
    "profile.friends": "Friends",
    "profile.photos": "Photos",
    "profile.posts": "Posts",
    "profile.allPhotos": "All Photos",
    "profile.detailedInfo": "Detailed Information",
    "profile.personalInfo": "Personal Information",
    "profile.changeCover": "Change Cover",
    "profile.addStory": "Add Story",
    "profile.addFriend": "Add Friend",
    "profile.message": "Message",
    "profile.videos": "Videos",
    "profile.seeAllFriends": "See All Friends",
    "profile.seeAllPhotos": "See All Photos",
    "profile.livesIn": "Lives in",
    "profile.works": "Works at",
    "profile.studied": "Studied at",
    "profile.from": "From",
    "profile.relationship": "Relationship",
    "profile.relationshipPlaceholder": "Enter your relationship status",
    "profile.notSpecified": "Not specified",
    "profile.single": "Single",
    "profile.inRelationship": "In a relationship",
    "profile.engaged": "Engaged",
    "profile.married": "Married",
    "profile.complicated": "It's complicated",
    "profile.fullName": "Full Name",
    "profile.enterLocation": "Enter location",
    "profile.enterBio": "Tell us about yourself...",
    "profile.enterWork": "Current work...",
    "profile.enterEducation": "School or university...",
    "profile.selectRelationship": "Select relationship status...",
    "profile.uploadProfilePicture": "Update profile picture",
    "profile.uploadCover": "Upload",
    "profile.pendingRequest": "Request sent",
    "profile.acceptRequest": "Confirm request",
    "profile.profilePicture": "Profile Picture",
    "profile.uploadPhoto": "Upload Photo",
    "profile.cancel": "Cancel",
    "profile.coverPhoto": "Cover Photo",
    "profile.saveChanges": "Save Changes",
    "profile.updateSuccess": "Profile updated successfully",

    // User Profile (Added from your request)
    "profile.editProfile": "Edit Profile",
    "profile.editProfileDesc": "Update your personal profile information",
    "profile.location": "Location",
    "profile.bio": "Bio",
    "profile.work": "Work",
    "profile.education": "Education",
    "profile.joined": "Joined",
    "profile.noPosts": "No posts yet",
    "profile.noFriends": "No friends yet",
    "profile.noPhotos": "No photos yet",
    "profile.userNotFound": "User not found",
    "profile.userNotFoundDesc": "This user does not exist or has been deleted.",
    "profile.backToHome": "Back to Home",
    "profile.loading": "Loading...",

    "profile.cancelRequest": "Cancel Request",
    "profile.options": "Options",
    "profile.blockUser": "Block",
    "profile.reportUser": "Report",
    "profile.blocked": "Blocked",
    "profile.unfriend": "Un Friend",
    "profile.acceptFriend": "Accept",
    "profile.rejectFriend": "Reject",
    "profile.unblockUser": "Unblock",

    // Common (Added from your request)
    "common.cancel": "Cancel",
    "common.saving": "Saving...",
    "common.save": "Save",

    // Post Creator
    "post.whatsOnYourMind": "What's on your mind?",
    "post.liveVideo": "Live Video",
    "post.photoVideo": "Photo/Video",
    "post.feelingActivity": "Feeling/Activity",
    "post.createPost": "Create Post",
    "post.addToYourPost": "Add to your post",
    "post.post": "Post",
    "post.public": "Public",
    "post.writeAComment": "Write a comment...",
    "post.viewMoreComments": "View more comments",
    "post.reply": "Reply",
    "post.replies": "replies",
    "post.viewReplies": "View",
    "post.hideReplies": "Hide replies",
    "post.replyTo": "Reply to",
    "post.loadingMorePosts": "Loading more posts...",
    "post.noPosts": "No posts to show yet.",

    // Post Actions
    "post.like": "Like",
    "post.comment": "Comment",
    "post.share": "Share",
    "post.likes": "likes",
    "post.comments": "comments",
    "post.shares": "shares",
    "post.savePost": "Save Post",
    "post.hidePost": "Hide Post",
    "post.reportPost": "Report Post",
    "post.viewFullPost": "View full post",
    "post.backToFeed": "Back to Feed",
    "post.relatedPosts": "Related Posts",
    "post.noRelatedPosts": "No related posts to show right now.",
    "post.viewDetails": "View Post Details",
    "post.copyLink": "Copy link",
    "post.linkCopied": "Link copied!",
    "post.shareOnFacebook": "Share on Facebook",
    "post.shareOnTwitter": "Share on Twitter",
    "post.shareViaEmail": "Share via email",
    "post.shareOptions": "Share options",
    "post.closeShareOptions": "Close share options",
    "post.viewPostDetails": "View Post Details",
    "post.feed": "Feed",
    "post.newest": "Newest",
    "post.popularToday": "Popular today",
    "post.popularThisWeek": "Popular this week",
    "post.popularThisMonth": "Popular this month",
    "post.popularThisYear": "Popular this year",
    "post.sortBy": "Sort by",
    "post.timeRange": "Time range",

    // Friends Page
    "friends.title": "Friends",
    "friends.friends": "Friends",
    "friends.outgoingRequests": "Outgoing",
    "friends.incomingRequests": "Incoming",
    "friends.suggestedFriends": "Suggested Friends",
    "friends.seeAll": "See All",
    "friends.mutualFriends": "mutual friends",
    "friends.add": "Add",
    "friends.yourFriends": "Your Friends",
    "friends.requests": "Friend Requests",
    "friends.suggestions": "Suggestions",
    "friends.allFriends": "All Friends",
    "friends.searchFriends": "Search friends",
    "friends.noSearchResults": "No friends match your search.",
    "friends.noFriends": "You don't have any friends yet.",
    "friends.noRequests": "You don't have any friend requests.",
    "friends.noSuggestions":
        "We don't have any friend suggestions for you right now.",
    "friends.message": "Message",
    "friends.accept": "Accept",
    "friends.cancel": "Cancel",
    "friends.unfriend": "Un Friend",
    "friends.reject": "Decline",
    "friends.addFriend": "Add Friend",
    "friends.online": "Online",
    "friends.offline": "Offline",


    // Games Page
    "games.title": "Games",
    "games.popular": "Popular",
    "games.new": "New",
    "games.myGames": "My Games",
    "games.trending": "Trending Games",
    "games.categories": "Categories",
    "games.leaderboard": "Leaderboard",
    "games.newReleases": "New Releases",
    "games.recentlyPlayed": "Recently Played",
    "games.recommended": "Recommended For You",
    "games.achievements": "Your Achievements",
    "games.friends": "Friends Playing",
    "games.explore": "Explore and relax with exciting games",
    "games.searchGames": "Search games...",
    "games.type": "Type",
    "games.status": "Status",
    "games.all": "All",
    "games.browser": "Browser",
    "games.embedded": "Embedded",
    "games.desktop": "Desktop",
    "games.playable": "Playable",
    "games.comingSoon": "Coming Soon",
    "games.maintenance": "Maintenance",
    "games.undefined": "Undefined",
    "games.noGamesFound": "No games found",
    "games.noGamesFoundDesc":
        "No games match your search. Try a different search or view all games.",
    "games.clearSearch": "Clear search",
    "games.clearFilters": "Clear filters",
    "games.viewAll": "View all",
    "games.browserGames": "Browser Games",
    "games.playInstantly": "Play instantly without installation",
    "games.playInBrowser": "Play directly in browser",
    "games.noInstallation": "No installation required",
    "games.smoothExperience": "Smooth experience",
    "games.embeddedGames": "Embedded Games",
    "games.fromGameService": "From GameService, play directly",
    "games.integratedFromGameService": "Integrated from GameService",
    "games.playDirectly": "Play directly in interface",
    "games.continuousUpdates": "Continuous updates",
    "games.desktopGames": "Desktop Games",
    "games.downloadAndPlay": "Download and play on your computer",
    "games.highQualityGraphics": "High quality graphics",
    "games.downloadFromGameService": "Download from GameService",
    "games.fullGameExperience": "Full game experience",
    "games.downloadComplete": "Download complete",
    "games.openToPlay": "Open file to play",

    // Footer
    "footer.copyright": "© 2023 PinkSocial",
  },
  vietnamese: {
    // Navigation
    "nav.home": "Trang chủ",
    "nav.messages": "Tin nhắn",
    "nav.friends": "Bạn bè",
    "nav.groups": "Nhóm",
    "nav.games": "Trò chơi",
    "nav.search": "Tìm kiếm...",

    // Groups Page
    "groups.create": "Tạo nhóm",
    "groups.createNew": "Tạo nhóm mới",
    "groups.createDescription":
        "Tạo một nhóm mới để kết nối với những người có cùng sở thích.",
    "groups.name": "Tên nhóm",
    "groups.namePlaceholder": "Nhập tên cho nhóm của bạn",
    "groups.description": "Mô tả",
    "groups.descriptionPlaceholder": "Nhóm của bạn nói về điều gì?",
    "groups.privacy": "Quyền riêng tư",
    "groups.privacyDescription":
        "Nhóm công khai có thể được tìm thấy trong tìm kiếm và bất kỳ ai cũng có thể tham gia. Nhóm riêng tư yêu cầu phê duyệt để tham gia.",
    "groups.public": "Công khai",
    "groups.private": "Riêng tư",
    "groups.cancel": "Hủy",
    "groups.yourGroups": "Nhóm của bạn",
    "groups.discover": "Khám phá",
    "groups.events": "Sự kiện",
    "groups.upcomingEvents": "Sự kiện sắp tới",
    "groups.recentDiscussions": "Thảo luận gần đây",
    "groups.suggested": "Nhóm đề xuất",
    "groups.members": "thành viên",
    "groups.join": "Tham gia nhóm",
    "groups.viewGroup": "Xem nhóm",
    "groups.search": "Tìm kiếm nhóm",
    "groups.loadMore": "Tải thêm",
    "groups.createEvent": "Tạo sự kiện",
    "groups.attending": "tham dự",
    "groups.interested": "Quan tâm",
    "groups.comments": "bình luận",
    "groups.noGroups": "Bạn chưa tham gia nhóm nào",
    "groups.noGroupsDescription":
        "Tạo một nhóm hoặc khám phá các nhóm để kết nối với những người có cùng sở thích.",
    "groups.noEvents": "Không có sự kiện sắp tới",
    "groups.noEventsDescription":
        "Không có sự kiện sắp tới trong các nhóm của bạn. Hãy tạo một sự kiện hoặc kiểm tra lại sau.",
    "groups.discussion": "Thảo luận",
    "groups.about": "Giới thiệu",
    "groups.media": "Phương tiện",
    "groups.files": "Tệp",
    "groups.photos": "Ảnh",
    "groups.addPhotos": "Thêm ảnh",
    "groups.groupInfo": "Thông tin nhóm",
    "groups.publicGroup": "Nhóm công khai",
    "groups.privateGroup": "Nhóm riêng tư",
    "groups.created": "Đã tạo",
    "groups.rules": "Quy tắc",
    "groups.notifications": "Thông báo",
    "groups.share": "Chia sẻ",
    "groups.options": "Tùy chọn",
    "groups.inviteFriends": "Mời bạn bè",
    "groups.inviteFriendsDescription": "Mời bạn bè của bạn tham gia nhóm này",
    "groups.muteNotifications": "Tắt thông báo",
    "groups.manageGroup": "Quản lý nhóm",
    "groups.reportGroup": "Báo cáo nhóm",
    "groups.leaveGroup": "Rời khỏi nhóm",
    "groups.leaveConfirmation": "Bạn có chắc chắn muốn rời khỏi nhóm này?",
    "groups.transferOwnership": "Chuyển quyền sở hữu",
    "groups.writePost": "Viết gì đó cho nhóm...",
    "groups.searchMembers": "Tìm kiếm thành viên",
    "groups.invite": "Mời",
    "groups.admin": "Quản trị viên",
    "groups.moderator": "Người điều hành",
    "groups.joined": "Đã tham gia",
    "groups.eventTitle": "Tiêu đề sự kiện",
    "groups.eventTitlePlaceholder": "Nhập tiêu đề sự kiện",
    "groups.eventDate": "Ngày & Giờ",
    "groups.eventLocation": "Địa điểm",
    "groups.eventLocationPlaceholder": "Nhập địa điểm sự kiện",
    "groups.eventDescription": "Mô tả",
    "groups.eventDescriptionPlaceholder": "Mô tả sự kiện của bạn",
    "groups.eventCover": "Ảnh bìa sự kiện",
    "groups.uploadEventCover": "Tải lên ảnh bìa sự kiện",
    "groups.createEventDescription":
        "Tạo một sự kiện mới cho các thành viên nhóm của bạn",
    "groups.done": "Hoàn thành",
    "groups.searchFriends": "Tìm kiếm bạn bè",
    "groups.settings": "Cài đặt nhóm",
    "groups.settingsDescription": "Quản lý cài đặt và quyền của nhóm",
    "groups.backToGroup": "Quay lại nhóm",
    "groups.general": "Chung",
    "groups.moderation": "Kiểm duyệt",
    "groups.dangerZone": "Khu vực nguy hiểm",
    "groups.dangerZoneDescription":
        "Những hành động này không thể hoàn tác. Hãy cẩn thận.",
    "groups.basicInfo": "Thông tin cơ bản",
    "groups.basicInfoDescription": "Thiết lập thông tin cơ bản về nhóm của bạn",
    "groups.groupImages": "Hình ảnh nhóm",
    "groups.groupImagesDescription": "Tải lên hình ảnh cho nhóm của bạn",
    "groups.groupAvatar": "Ảnh đại diện nhóm",
    "groups.uploadPhoto": "Tải lên ảnh",
    "groups.uploadCover": "Tải lên ảnh bìa",
    "groups.addRule": "Thêm quy tắc",
    "groups.add": "Thêm",
    "groups.saveChanges": "Lưu thay đổi",
    "groups.changesSaved": "Đã lưu thay đổi thành công",
    "groups.deleteGroup": "Xóa nhóm",
    "groups.deleteGroupDescription":
        "Khi bạn xóa một nhóm, không thể hoàn tác. Hãy chắc chắn.",
    "groups.deleteGroupTitle": "Xóa nhóm",
    "groups.deleteGroupConfirmation":
        "Bạn có chắc chắn muốn xóa nhóm này? Tất cả nội dung sẽ bị xóa vĩnh viễn.",
    "groups.deleteGroupWarning": "Hành động này không thể hoàn tác.",
    "groups.groupDeleted": "Đã xóa nhóm thành công",
    "groups.transferOwnershipTitle": "Chuyển quyền sở hữu nhóm",
    "groups.transferOwnershipDescription":
        "Chọn một thành viên để chuyển quyền sở hữu nhóm",
    "groups.transfer": "Chuyển",
    "groups.ownershipTransferred": "Đã chuyển quyền sở hữu nhóm thành công",
    "groups.manageMembers": "Quản lý thành viên",
    "groups.manageMembersDescription":
        "Thêm hoặc xóa thành viên và gán vai trò",
    "groups.removeMod": "Xóa quyền điều hành",
    "groups.makeMod": "Đặt làm người điều hành",
    "groups.removeModTitle": "Xóa người điều hành",
    "groups.makeModTitle": "Đặt làm người điều hành",
    "groups.removeModDescription":
        "Bạn có chắc chắn muốn xóa quyền điều hành của {name}?",
    "groups.makeModDescription":
        "Bạn có chắc chắn muốn đặt {name} làm người điều hành?",
    "groups.remove": "Xóa",
    "groups.removeMemberTitle": "Xóa thành viên",
    "groups.removeMemberDescription":
        "Bạn có chắc chắn muốn xóa {name} khỏi nhóm?",
    "groups.inviteMembers": "Mời thành viên",
    "groups.contentModeration": "Kiểm duyệt nội dung",
    "groups.contentModerationDescription":
        "Quản lý phê duyệt nội dung và nội dung bị báo cáo",
    "groups.approvalSettings": "Cài đặt phê duyệt",
    "groups.approvalSettingsDescription":
        "Kiểm soát nội dung nào cần phê duyệt trước khi được đăng",
    "groups.approveNewMembers": "Phê duyệt thành viên mới",
    "groups.approveNewMembersDescription":
        "Yêu cầu quản trị viên phê duyệt thành viên mới",
    "groups.approveNewPosts": "Phê duyệt bài đăng mới",
    "groups.approveNewPostsDescription":
        "Yêu cầu quản trị viên phê duyệt bài đăng mới",
    "groups.reportedContent": "Nội dung bị báo cáo",
    "groups.reportedContentDescription":
        "Xem xét và thực hiện hành động đối với nội dung bị báo cáo",
    "groups.reportedBy": "Được báo cáo bởi {name}",
    "groups.pending": "Đang chờ",
    "groups.reviewed": "Đã xem xét",
    "groups.contentType": "Loại nội dung",
    "groups.post": "Bài đăng",
    "groups.comment": "Bình luận",
    "groups.reason": "Lý do",
    "groups.ignore": "Bỏ qua",
    "groups.removeContent": "Xóa nội dung",
    "groups.notificationSettings": "Cài đặt thông báo",
    "groups.notificationSettingsDescription":
        "Kiểm soát thông báo bạn nhận được từ nhóm này",
    "groups.newMemberNotifications": "Thông báo thành viên mới",
    "groups.newMemberNotificationsDescription":
        "Nhận thông báo khi có người tham gia nhóm",
    "groups.newPostNotifications": "Thông báo bài đăng mới",
    "groups.newPostNotificationsDescription":
        "Nhận thông báo khi có người đăng bài trong nhóm",
    "groups.commentNotifications": "Thông báo bình luận",
    "groups.commentNotificationsDescription":
        "Nhận thông báo khi có người bình luận về bài đăng của bạn",
    "groups.eventNotifications": "Thông báo sự kiện",
    "groups.eventNotificationsDescription": "Nhận thông báo về sự kiện sắp tới",
    "groups.createGroup": "Tạo nhóm",
    "groups.creating": "Đang tạo...",
    "groups.rulesDescription":
        "Đặt quy tắc cho các thành viên nhóm của bạn tuân theo",
    "groups.noRulesYet":
        "Chưa có quy tắc nào được thêm. Thêm một số quy tắc để giúp thành viên hiểu những gì được mong đợi.",
    "groups.myGroups": "Nhóm của tôi",
    "groups.createdByYou": "Được tạo bởi bạn",
    "groups.adminRights": "Quyền quản trị",
    "groups.allGroups": "Tất cả nhóm",
    "groups.owner": "Chủ sở hữu",
    "groups.pendingPosts": "bài đăng đang chờ",
    "groups.pendingMembers": "thành viên đang chờ",
    "groups.unreadMessages": "tin nhắn chưa đọc",
    "groups.reviewPosts": "Xem xét bài đăng",
    "groups.reviewMembers": "Xem xét thành viên",
    "groups.enableNotifications": "Bật thông báo",
    "groups.edit": "Chỉnh sửa nhóm",
    "groups.editGroup": "Chỉnh sửa nhóm",
    "groups.noCreatedGroups": "Bạn chưa tạo nhóm nào",
    "groups.noAdminGroups": "Bạn không có quyền quản trị trong bất kỳ nhóm nào",
    "groups.adminGroupsDescription":
        "Khi bạn được đặt làm quản trị viên của một nhóm, nó sẽ xuất hiện ở đây",
    "groups.noSearchResults": "Không có nhóm nào phù hợp với tìm kiếm của bạn",
    "groups.tryDifferentSearch": "Thử một từ khóa tìm kiếm khác",
    "groups.groupManagement": "Quản lý nhóm",
    "groups.groupManagementDescription": "Tạo và quản lý nhóm của bạn",
    "groups.invitations": "Lời mời",
    "groups.noPermission": "Bạn không có quyền chỉnh sửa nhóm này",
    "groups.backToGroups": "Quay lại nhóm",
    "groups.savingError":
        "Đã xảy ra lỗi khi lưu thay đổi của bạn. Vui lòng thử lại.",
    "groups.saving": "Đang lưu...",
    "groups.title": "Nhóm",
    "groups.groupSettings": "Cài đặt nhóm",
    "groups.changeCover": "Đổi ảnh bìa",

    // Search
    "search.keywords": "Từ khóa",
    "search.keyword": "Từ khóa",
    "search.people": "Người dùng",
    "search.person": "Người dùng",
    "search.posts": "Bài viết",
    "search.post": "Bài viết",
    "search.groups": "Nhóm",
    "search.group": "Nhóm",
    "search.games": "Trò chơi",
    "search.game": "Trò chơi",
    "search.viewAll": "Xem tất cả kết quả",
    "search.results": "Kết quả tìm kiếm",
    "search.placeholder": "Tìm kiếm trên PinkSocial...",
    "search.search": "Tìm kiếm",
    "search.all": "Tất cả",
    "search.filters": "Bộ lọc",
    "search.date": "Thời gian",
    "search.anyTime": "Bất kỳ lúc nào",
    "search.past24h": "24 giờ qua",
    "search.pastWeek": "Tuần qua",
    "search.pastMonth": "Tháng qua",
    "search.source": "Nguồn",
    "search.fromFriends": "Từ bạn bè",
    "search.fromGroups": "Từ nhóm",
    "search.public": "Công khai",
    "search.seeAll": "Xem tất cả",

    // Messages
    "messages.timeline": "Dòng thời gian",
    "messages.messages": "Tin nhắn",
    "messages.conversations": "Cuộc trò chuyện",
    "messages.searchMessages": "Tìm kiếm tin nhắn",
    "messages.whatsHappening": "Điều gì đang xảy ra?",
    "messages.send": "Gửi",
    "messages.typeMessage": "Nhập tin nhắn...",
    "messages.noMessages": "Chưa có tin nhắn nào.",
    "messages.noSearchResults":
        "Không có tin nhắn nào phù hợp với tìm kiếm của bạn.",
    "messages.noConversations": "Chưa có cuộc trò chuyện nào.",
    "messages.selectConversation":
        "Chọn một cuộc trò chuyện để bắt đầu nhắn tin",
    "messages.userAvatar": "Ảnh đại diện người dùng",
    "messages.user.janeDoe": "Jane Doe",
    "messages.user.johnSmith": "John Smith",
    "messages.user.sarahJohnson": "Sarah Johnson",
    "messages.user.michaelChen": "Michael Chen",
    "messages.user.currentUser": "Người dùng hiện tại",
    "messages.sampleText.greeting": "Chào bạn, hôm nay bạn thế nào?",
    "messages.sampleText.movie": "Bạn đã xem bộ phim mới ra mắt chưa?",
    "messages.sampleText.thanks": "Cảm ơn vì đã giúp đỡ với dự án!",
    "messages.sampleText.coffee": "Hẹn gặp nhau uống cà phê vào tuần sau nhé!",
    "messages.sampleText.dayGoing": "Chào! Ngày hôm nay của bạn thế nào?",
    "messages.sampleText.appFeatures":
        "Chào Jane! Mình khỏe, cảm ơn đã hỏi thăm. Mình đang làm một số tính năng mới cho ứng dụng.",
    "messages.sampleText.whatFeatures":
        "Nghe thú vị đấy! Bạn đang làm những tính năng gì vậy?",
    "messages.sampleText.messagingSystem":
        "Mình đang thêm hệ thống nhắn tin mới với khả năng chia sẻ phương tiện tốt hơn.",
    "messages.sampleText.testIt":
        "Nghe thật tuyệt! Mình rất muốn thử nó khi nó sẵn sàng.",
    "messages.sampleText.notYet": "Chưa! Nó có hay không?",
    "messages.sampleText.tuesday":
        "Nghe tốt đấy! Thứ Ba lúc 2 giờ chiều được không?",
    "messages.sampleText.usualPlace":
        "Tuyệt! Hẹn gặp tại địa điểm thường lệ nhé.",

    // Time translations
    "time.just now": "vừa xong",
    "time.1 minute ago": "1 phút trước",
    "time.2 minutes ago": "2 phút trước",
    "time.5 minutes ago": "5 phút trước",
    "time.10 minutes ago": "10 phút trước",
    "time.15 minutes ago": "15 phút trước",
    "time.30 minutes ago": "30 phút trước",
    "time.45 minutes ago": "45 phút trước",
    "time.1 hour ago": "1 giờ trước",
    "time.2 hours ago": "2 giờ trước",
    "time.3 hours ago": "3 giờ trước",
    "time.4 hours ago": "4 giờ trước",
    "time.5 hours ago": "5 giờ trước",
    "time.yesterday": "hôm qua",
    "time.2 days ago": "2 ngày trước",
    "time.3 days ago": "3 ngày trước",
    "time.last week": "tuần trước",
    "time.2 weeks ago": "2 tuần trước",
    "time.last month": "tháng trước",
    "time.2 months ago": "2 tháng trước",
    "time.3 months ago": "3 tháng trước",
    "time.last year": "năm trước",
    "time.2 years ago": "2 năm trước",
    "time.3 years ago": "3 năm trước",
    "time.a long time ago": "rất lâu trước đây",

    // User Profile (Existing)
    "profile.profile": "Trang cá nhân",
    "profile.language": "Ngôn ngữ",
    "profile.logout": "Đăng xuất",
    "profile.about": "Giới thiệu",
    "profile.friends": "Bạn bè",
    "profile.photos": "Hình ảnh",
    "profile.posts": "Bài viết",
    "profile.allPhotos": "Tất cả hình ảnh",
    "profile.detailedInfo": "Thông tin chi tiết",
    "profile.personalInfo": "Thông tin cá nhân",
    "profile.changeCover": "Thay đổi ảnh bìa",
    "profile.addStory": "Thêm tin",
    "profile.addFriend": "Kết bạn",
    "profile.message": "Nhắn tin",
    "profile.videos": "Video",
    "profile.seeAllFriends": "Xem tất cả bạn bè",
    "profile.seeAllPhotos": "Xem tất cả hình ảnh",
    "profile.livesIn": "Sống tại",
    "profile.works": "Làm việc tại",
    "profile.studied": "Đã học tại",
    "profile.from": "Đến từ",
    "profile.relationship": "Tình trạng mối quan hệ",
    "profile.relationshipPlaceholder": "Nhập tình trạng mối quan hệ của bạn",
    "profile.notSpecified": "Không xác định",
    "profile.single": "Độc thân",
    "profile.inRelationship": "Đang hẹn hò",
    "profile.engaged": "Đã đính hôn",
    "profile.married": "Đã kết hôn",
    "profile.complicated": "Phức tạp",
    "profile.fullName": "Họ và tên",
    "profile.enterLocation": "Nhập địa điểm",
    "profile.enterBio": "Giới thiệu về bản thân...",
    "profile.enterWork": "Công việc hiện tại...",
    "profile.enterEducation": "Trường học...",
    "profile.selectRelationship": "Chọn tình trạng...",
    "profile.uploadProfilePicture": "Cập nhật ảnh đại diện",
    "profile.uploadCover": "Tải lên",
    "profile.pendingRequest": "Đã gửi lời mời",
    "profile.acceptRequest": "Xác nhận lời mời",
    "profile.profilePicture": "Ảnh đại diện",
    "profile.uploadPhoto": "Tải ảnh lên",
    "profile.cancel": "Hủy",
    "profile.coverPhoto": "Ảnh bìa",
    "profile.saveChanges": "Lưu thay đổi",
    "profile.updateSuccess": "Cập nhật trang cá nhân thành công",

    // User Profile (Added from your request)
    "profile.editProfile": "Chỉnh sửa hồ sơ",
    "profile.editProfileDesc": "Cập nhật thông tin hồ sơ cá nhân của bạn",
    "profile.location": "Địa điểm",
    "profile.bio": "Giới thiệu",
    "profile.work": "Công việc",
    "profile.joined": "Tham gia",
    "profile.noPosts": "Chưa có bài viết nào",
    "profile.noFriends": "Chưa có bạn bè nào",
    "profile.noPhotos": "Chưa có ảnh nào",
    "profile.userNotFound": "Không tìm thấy người dùng",
    "profile.userNotFoundDesc": "Người dùng này không tồn tại hoặc đã bị xóa.",
    "profile.backToHome": "Quay về trang chủ",
    "profile.loading": "Đang tải thông tin...",

    "profile.acceptFriend": "Chấp nhận",
    "profile.rejectFriend": "Từ chối",

    "profile.cancelRequest": "Hủy yêu cầu",
    "profile.options": "Lựa chọn",
    "profile.blockUser": "Chặn",
    "profile.reportUser": "Báo cáo",
    "profile.blocked": "Đã bị chặn",
    "profile.unfriend": "Hủy bạn bè",
    "profile.unblockUser": "Hủy chặn",

    // Common (Added from your request)
    "common.cancel": "Hủy",
    "common.saving": "Đang lưu...",
    "common.save": "Lưu",

    // Post Creator
    "post.whatsOnYourMind": "Bạn đang nghĩ gì?",
    "post.liveVideo": "Video trực tiếp",
    "post.photoVideo": "Hình ảnh/Video",
    "post.feelingActivity": "Cảm xúc/Hoạt động",
    "post.createPost": "Tạo bài viết",
    "post.addToYourPost": "Thêm vào bài viết của bạn",
    "post.post": "Đăng",
    "post.public": "Công khai",
    "post.writeAComment": "Viết bình luận...",
    "post.viewMoreComments": "Xem thêm bình luận",
    "post.reply": "Phản hồi",
    "post.replies": "phản hồi",
    "post.viewReplies": "Xem",
    "post.hideReplies": "Ẩn phản hồi",
    "post.replyTo": "Phản hồi cho",
    "post.loadingMorePosts": "Đang tải thêm bài viết...",
    "post.noPosts": "Chưa có bài viết nào để hiển thị.",

    // Post Actions
    "post.like": "Thích",
    "post.comment": "Bình luận",
    "post.share": "Chia sẻ",
    "post.likes": "lượt thích",
    "post.comments": "bình luận",
    "post.shares": "lượt chia sẻ",
    "post.savePost": "Lưu bài viết",
    "post.hidePost": "Ẩn bài viết",
    "post.reportPost": "Báo cáo bài viết",
    "post.viewFullPost": "Xem bài viết đầy đủ",
    "post.backToFeed": "Quay lại bảng tin",
    "post.relatedPosts": "Bài viết liên quan",
    "post.noRelatedPosts": "Không có bài viết liên quan nào để hiển thị.",
    "post.viewDetails": "Xem chi tiết bài viết",
    "post.copyLink": "Sao chép liên kết",
    "post.linkCopied": "Đã sao chép liên kết!",
    "post.shareOnFacebook": "Chia sẻ lên Facebook",
    "post.shareOnTwitter": "Chia sẻ lên Twitter",
    "post.shareViaEmail": "Chia sẻ qua email",
    "post.shareOptions": "Tùy chọn chia sẻ",
    "post.closeShareOptions": "Đóng tùy chọn chia sẻ",
    "post.viewPostDetails": "Xem chi tiết bài viết",
    "post.feed": "Bảng tin",
    "post.newest": "Mới nhất",
    "post.popularToday": "Phổ biến nhất ngày",
    "post.popularThisWeek": "Phổ biến nhất tuần",
    "post.popularThisMonth": "Phổ biến nhất tháng",
    "post.popularThisYear": "Phổ biến nhất năm",
    "post.sortBy": "Sắp xếp theo",
    "post.timeRange": "Khoảng thời gian",

    // Friends Page
    "friends.title": "Bạn bè",
    "friends.friends": "Bạn bè",
    "friends.outgoingRequests": "Lời mời đã gửi",
    "friends.incomingRequests": "Lời mời đã nhận",
    "friends.suggestedFriends": "Gợi ý kết bạn",
    "friends.seeAll": "Xem tất cả",
    "friends.mutualFriends": "bạn chung",
    "friends.add": "Thêm",
    "friends.yourFriends": "Bạn bè của bạn",
    "friends.requests": "Lời mời kết bạn",
    "friends.suggestions": "Gợi ý",
    "friends.allFriends": "Tất cả bạn bè",
    "friends.searchFriends": "Tìm kiếm bạn bè",
    "friends.noSearchResults": "Không tìm thấy bạn bè phù hợp.",
    "friends.noFriends": "Bạn chưa có bạn bè nào.",
    "friends.noRequests": "Bạn không có lời mời kết bạn nào.",
    "friends.noSuggestions":
      "Hiện tại chúng tôi không có gợi ý kết bạn nào cho bạn.",
    "friends.message": "Nhắn tin",
    "friends.accept": "Chấp nhận",
    "friends.cancel": "Hủy lời mời",
    "friends.unfriend": "Hủy bạn bè",
    "friends.reject": "Từ chối",
    "friends.addFriend": "Kết bạn",
    "friends.online": "Trực tuyến",
    "friends.offline": "Ngoại tuyến",


    // Games Page
    "games.title": "Trò chơi",
    "games.popular": "Phổ biến",
    "games.new": "Mới",
    "games.myGames": "Trò chơi của tôi",
    "games.trending": "Trò chơi thịnh hành",
    "games.categories": "Danh mục",
    "games.leaderboard": "Bảng xếp hạng",
    "games.newReleases": "Mới phát hành",
    "games.recentlyPlayed": "Đã chơi gần đây",
    "games.recommended": "Đề xuất cho bạn",
    "games.achievements": "Thành tích của bạn",
    "games.friends": "Bạn bè đang chơi",
    "games.explore": "Khám phá và thư giãn với các trò chơi hấp dẫn",
    "games.searchGames": "Tìm kiếm trò chơi...",
    "games.type": "Loại",
    "games.status": "Trạng thái",
    "games.all": "Tất cả",
    "games.browser": "Trình duyệt",
    "games.embedded": "Tích hợp",
    "games.desktop": "Máy tính",
    "games.playable": "Có thể chơi",
    "games.comingSoon": "Sắp ra mắt",
    "games.maintenance": "Bảo trì",
    "games.undefined": "Không xác định",
    "games.noGamesFound": "Không tìm thấy trò chơi",
    "games.noGamesFoundDesc":
      "Không có trò chơi nào phù hợp với tìm kiếm của bạn. Hãy thử tìm kiếm khác hoặc xem tất cả trò chơi.",
    "games.clearSearch": "Xóa tìm kiếm",
    "games.clearFilters": "Xóa bộ lọc",
    "games.viewAll": "Xem tất cả",
    "games.browserGames": "Trò chơi trình duyệt",
    "games.playInstantly": "Chơi ngay không cần cài đặt",
    "games.playInBrowser": "Chơi trực tiếp trên trình duyệt",
    "games.noInstallation": "Không cần cài đặt",
    "games.smoothExperience": "Trải nghiệm mượt mà",
    "games.embeddedGames": "Game tích hợp",
    "games.fromGameService": "Từ GameService, chơi trực tiếp",
    "games.integratedFromGameService": "Tích hợp từ GameService",
    "games.playDirectly": "Chơi ngay trên giao diện",
    "games.continuousUpdates": "Cập nhật liên tục",
    "games.desktopGames": "Game máy tính",
    "games.downloadAndPlay": "Tải về và chơi trên máy tính",
    "games.highQualityGraphics": "Đồ họa chất lượng cao",
    "games.downloadFromGameService": "Tải về từ GameService",
    "games.fullGameExperience": "Trải nghiệm game đầy đủ",
    "games.downloadComplete": "Tải xuống hoàn tất",
    "games.openToPlay": "Mở tệp để chơi",

    // Footer
    "footer.copyright": "© 2023 PinkSocial",
  },
};

const LanguageContext = createContext<LanguageContextType>(
  {} as LanguageContextType,
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      return (savedLanguage as Language) || "english";
    }
    return "english";
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    if (typeof window !== "undefined") {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage);
    }
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in ${language}`);
      const englishTranslation = translations.english[key];
      if (englishTranslation) return englishTranslation;
      return key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
