spring:
  application:
    name: authservice

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  # Bật scheduled tasks
  task:
    scheduling:
      enabled: true
    execution: # Cấu hình thread pool cho @Async
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      add-mappings: false


security:
  jwt:
    secret: 'mysecretkeyforhs256whichislongenough'  # Giá trị mặc định
    access-token-expiration: 86400000 # 1 ngày
    refresh-token-expiration: 604800000 # 1 tuần
#    access-token-expiration: 10000 # 10 giây
#    refresh-token-expiration: 30000 # 30 giay