spring:
  application:
    name: authservice

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  web:
    resources:
      add-mappings: false

security:
  jwt:
    secret: 'mysecretkeyforhs256whichislongenough'  # Giá trị mặc định
    access-token-expiration: 3600000 # 1 giờ
    refresh-token-expiration: 86400000 # 1 ngày
#    access-token-expiration: 10000 # 10 giây
#    refresh-token-expiration: 30000 # 30 giay