FROM kong:latest

USER root

# Cài đặt curl và bash
RUN apt-get update && \
    apt-get install -y curl bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Tạo thư mục cấu hình
RUN mkdir -p /etc/kong/config

# Sao chép script cấu hình
COPY setup-kong.sh /etc/kong/config/setup-kong.sh
RUN chmod +x /etc/kong/config/setup-kong.sh

USER kong 